version: '3.8'

services:
  minio:
    image: bitnami/minio:2021.3.1
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    volumes:
      - ./data/minio-persistence:/data
      - ./data/minio-persistence/certs:/certs
    ports:
      - 9000:9000

  filestorage:
    image: spring-boot-minio-ex:0.0.1
    container_name: spring-boot-minio-ex
    environment:
      PROJECT_PROFILES: "dev" #dev,prod
      SERVER-PATH: "/api"
      API_DOCS_PATH: "/api-docs"
      SWAGGER_UI_ENABLED: "true"
      SWAGGER_UI_PATH: "/documentation"
      MINIO_URL: http://minio:9000
      MINIO_BUCKET: "file-storage"
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MAX_FILE_SIZE: "20MB"
      MAX_REQUEST_SIZE: "20MB"
      FILE-SIZE-THRESHOLD: "2KB"
    ports:
      - 8080:8080
